// Türkiye İl ve İlçe Listesi
export const turkiyeIller = [
  { name: 'Adana', plaka: '01', ilceler: ['Seyhan', 'Yüreğir', 'Çukurova', 'Sarıçam', 'Ceyhan', 'Kozan', 'İmamoğlu', 'Karaisalı', 'Karataş', 'Pozantı', 'Tufanbeyli', 'Feke', 'Saimbeyli', 'Aladağ'] },
  { name: 'Adıyaman', plaka: '02', ilceler: ['Merkez', 'Besni', 'Çelikhan', 'Gerger', 'Gölbaşı', 'Kahta', 'Samsat', 'Sincik', 'Tut'] },
  { name: 'Afyonkarahisar', plaka: '03', ilceler: ['Merkez', 'Başmakçı', 'Bayat', 'Bolvadin', 'Çay', 'Çobanlar', 'Dazkırı', 'Dinar', 'Emirdağ', 'Evciler', 'Hocalar', 'İhsaniye', 'İscehisar', 'Kızılören', 'Sandıklı', 'Sinanpaşa', 'Sultandağı', 'Şuhut'] },
  { name: 'Ağrı', plaka: '04', ilceler: ['Merkez', 'Diyadin', 'Doğubayazıt', 'Eleşkirt', 'Hamur', 'Patnos', 'Taşlıçay', 'Tutak'] },
  { name: 'Amasya', plaka: '05', ilceler: ['Merkez', 'Göynücek', 'Gümüşhacıköy', 'Hamamözü', 'Merzifon', 'Suluova', 'Taşova'] },
  { name: 'Ankara', plaka: '06', ilceler: ['Altındağ', 'Ayaş', 'Bala', 'Beypazarı', 'Çamlıdere', 'Çankaya', 'Çubuk', 'Elmadağ', 'Güdül', 'Haymana', 'Kalecik', 'Kızılcahamam', 'Nallıhan', 'Polatlı', 'Şereflikoçhisar', 'Yenimahalle', 'Gölbaşı', 'Keçiören', 'Mamak', 'Sincan', 'Kazan', 'Akyurt', 'Etimesgut', 'Evren', 'Pursaklar'] },
  { name: 'Antalya', plaka: '07', ilceler: ['Alanya', 'Elmalı', 'Finike', 'Gazipaşa', 'Gündoğmuş', 'Kaş', 'Kemer', 'Korkuteli', 'Kumluca', 'Manavgat', 'Serik', 'Akseki', 'Aksu', 'Demre', 'Döşemealtı', 'İbradı', 'Kale', 'Konyaaltı', 'Muratpaşa', 'Kepez'] },
  { name: 'Artvin', plaka: '08', ilceler: ['Merkez', 'Ardanuç', 'Arhavi', 'Borçka', 'Hopa', 'Murgul', 'Şavşat', 'Yusufeli'] },
  { name: 'Aydın', plaka: '09', ilceler: ['Merkez', 'Bozdoğan', 'Çine', 'Germencik', 'Karacasu', 'Koçarlı', 'Kuşadası', 'Kuyucak', 'Nazilli', 'Söke', 'Sultanhisar', 'Yenipazar', 'Buharkent', 'İncirliova', 'Karpuzlu', 'Köşk', 'Didim'] },
  { name: 'Balıkesir', plaka: '10', ilceler: ['Merkez', 'Ayvalık', 'Balya', 'Bandırma', 'Bigadiç', 'Burhaniye', 'Dursunbey', 'Edremit', 'Erdek', 'Gönen', 'Havran', 'İvrindi', 'Kepsut', 'Manyas', 'Savaştepe', 'Sındırgı', 'Susurluk', 'Gömeç', 'Marmara'] },
  { name: 'Bilecik', plaka: '11', ilceler: ['Merkez', 'Bozüyük', 'Gölpazarı', 'Osmaneli', 'Pazaryeri', 'Söğüt', 'Yenipazar', 'İnhisar'] },
  { name: 'Bingöl', plaka: '12', ilceler: ['Merkez', 'Adaklı', 'Genç', 'Karlıova', 'Kiğı', 'Solhan', 'Yayladere', 'Yedisu'] },
  { name: 'Bitlis', plaka: '13', ilceler: ['Merkez', 'Adilcevaz', 'Ahlat', 'Güroymak', 'Hizan', 'Mutki', 'Tatvan'] },
  { name: 'Bolu', plaka: '14', ilceler: ['Merkez', 'Gerede', 'Göynük', 'Kıbrıscık', 'Mengen', 'Mudurnu', 'Seben', 'Dörtdivan', 'Yeniçağa'] },
  { name: 'Burdur', plaka: '15', ilceler: ['Merkez', 'Ağlasun', 'Altınyayla', 'Bucak', 'Çavdır', 'Çeltikçi', 'Gölhisar', 'Karamanlı', 'Kemer', 'Tefenni', 'Yeşilova'] },
  { name: 'Bursa', plaka: '16', ilceler: ['Osmangazi', 'Nilüfer', 'Yıldırım', 'Mudanya', 'Gemlik', 'Orhangazi', 'İnegöl', 'Yenişehir', 'Karacabey', 'Mustafakemalpaşa', 'Marmara', 'Gürsu', 'Kestel', 'Harmancık', 'Büyükorhan', 'Orhaneli', 'Keles'] },
  { name: 'Çanakkale', plaka: '17', ilceler: ['Merkez', 'Ayvacık', 'Bayramiç', 'Biga', 'Bozcaada', 'Çan', 'Eceabat', 'Ezine', 'Gelibolu', 'Gökçeada', 'Lapseki', 'Yenice'] },
  { name: 'Çankırı', plaka: '18', ilceler: ['Merkez', 'Atkaracalar', 'Bayramören', 'Çerkeş', 'Eldivan', 'Ilgaz', 'Kızılırmak', 'Korgun', 'Kurşunlu', 'Orta', 'Şabanözü', 'Yapraklı'] },
  { name: 'Çorum', plaka: '19', ilceler: ['Merkez', 'Alaca', 'Bayat', 'Boğazkale', 'Dodurga', 'İskilip', 'Kargı', 'Laçin', 'Mecitözü', 'Oğuzlar', 'Ortaköy', 'Osmancık', 'Sungurlu', 'Uğurludağ'] },
  { name: 'Denizli', plaka: '20', ilceler: ['Merkez', 'Acıpayam', 'Babadağ', 'Baklan', 'Bekilli', 'Beyağaç', 'Bozkurt', 'Buldan', 'Çal', 'Çameli', 'Çardak', 'Çivril', 'Güney', 'Honaz', 'Kale', 'Sarayköy', 'Serinhisar', 'Tavas', 'Pamukkale'] },
  { name: 'Diyarbakır', plaka: '21', ilceler: ['Bağlar', 'Bismil', 'Çermik', 'Çınar', 'Çüngüş', 'Dicle', 'Eğil', 'Ergani', 'Hani', 'Hazro', 'Kocaköy', 'Kulp', 'Lice', 'Silvan', 'Sur', 'Yenişehir', 'Kayapınar'] },
  { name: 'Edirne', plaka: '22', ilceler: ['Merkez', 'Enez', 'Havsa', 'İpsala', 'Keşan', 'Lalapaşa', 'Meriç', 'Süloğlu', 'Uzunköprü'] },
  { name: 'Elazığ', plaka: '23', ilceler: ['Merkez', 'Ağın', 'Alacakaya', 'Arıcak', 'Baskil', 'Karakoçan', 'Keban', 'Kovancılar', 'Maden', 'Palu', 'Sivrice'] },
  { name: 'Erzincan', plaka: '24', ilceler: ['Merkez', 'Çayırlı', 'İliç', 'Kemah', 'Kemaliye', 'Otlukbeli', 'Refahiye', 'Tercan', 'Üzümlü'] },
  { name: 'Erzurum', plaka: '25', ilceler: ['Merkez', 'Aşkale', 'Çat', 'Hınıs', 'Horasan', 'İspir', 'Karaçoban', 'Karayazı', 'Köprüköy', 'Narman', 'Oltu', 'Olur', 'Pasinler', 'Şenkaya', 'Tekman', 'Tortum', 'Uzundere', 'Pazaryolu', 'Aziziye', 'Yakutiye', 'Palandöken'] },
  { name: 'Eskişehir', plaka: '26', ilceler: ['Merkez', 'Alpu', 'Beylikova', 'Çifteler', 'Günyüzü', 'Han', 'İnönü', 'Mahmudiye', 'Mihalgazi', 'Mihalıççık', 'Sarıcakaya', 'Seyitgazi', 'Sivrihisar', 'Tepebaşı', 'Odunpazarı'] },
  { name: 'Gaziantep', plaka: '27', ilceler: ['Şahinbey', 'Şehitkamil', 'Oğuzeli', 'Nizip', 'İslahiye', 'Nurdağı', 'Karkamış', 'Araban', 'Yavuzeli'] },
  { name: 'Giresun', plaka: '28', ilceler: ['Merkez', 'Alucra', 'Bulancak', 'Çanakçı', 'Dereli', 'Doğankent', 'Espiye', 'Eynesil', 'Görele', 'Güce', 'Keşap', 'Piraziz', 'Şebinkarahisar', 'Tirebolu', 'Yağlıdere'] },
  { name: 'Gümüşhane', plaka: '29', ilceler: ['Merkez', 'Kelkit', 'Şiran', 'Torul', 'Köse', 'Kürtün'] },
  { name: 'Hakkari', plaka: '30', ilceler: ['Merkez', 'Çukurca', 'Şemdinli', 'Yüksekova'] },
  { name: 'Hatay', plaka: '31', ilceler: ['Antakya', 'Altınözü', 'Belen', 'Dörtyol', 'Erzin', 'Hassa', 'İskenderun', 'Kırıkhan', 'Kumlu', 'Reyhanlı', 'Samandağ', 'Yayladağı', 'Arsuz', 'Defne', 'Payas'] },
  { name: 'Isparta', plaka: '32', ilceler: ['Merkez', 'Aksu', 'Atabey', 'Eğirdir', 'Gelendost', 'Gönen', 'Keçiborlu', 'Senirkent', 'Sütçüler', 'Şarkikaraağaç', 'Uluborlu', 'Yalvaç', 'Yenişarbademli'] },
  { name: 'İçel (Mersin)', plaka: '33', ilceler: ['Akdeniz', 'Mezitli', 'Toroslar', 'Yenişehir', 'Anamur', 'Aydıncık', 'Bozyazı', 'Çamlıyayla', 'Erdemli', 'Gülnar', 'Mut', 'Silifke', 'Tarsus'] },
  { name: 'İstanbul', plaka: '34', ilceler: ['Adalar', 'Bakırköy', 'Beşiktaş', 'Beykoz', 'Beyoğlu', 'Çatalca', 'Eyüp', 'Fatih', 'Gaziosmanpaşa', 'Kadıköy', 'Kartal', 'Sarıyer', 'Silivri', 'Şile', 'Şişli', 'Üsküdar', 'Zeytinburnu', 'Büyükçekmece', 'Kağıthane', 'Küçükçekmece', 'Pendik', 'Ümraniye', 'Bayrampaşa', 'Avcılar', 'Bağcılar', 'Bahçelievler', 'Güngören', 'Maltepe', 'Sultanbeyli', 'Tuzla', 'Esenler', 'Arnavutköy', 'Ataşehir', 'Başakşehir', 'Beylikdüzü', 'Çekmeköy', 'Esenyurt', 'Sancaktepe', 'Sultangazi'] },
  { name: 'İzmir', plaka: '35', ilceler: ['Aliağa', 'Bayındır', 'Bergama', 'Bornova', 'Çeşme', 'Dikili', 'Foça', 'Karaburun', 'Karşıyaka', 'Kemalpaşa', 'Kınık', 'Kiraz', 'Menemen', 'Ödemiş', 'Seferihisar', 'Selçuk', 'Tire', 'Torbalı', 'Urla', 'Beydağ', 'Buca', 'Konak', 'Menderes', 'Balçova', 'Çiğli', 'Gaziemir', 'Narlıdere', 'Güzelbahçe', 'Bayraklı', 'Karabağlar'] },
  { name: 'Kars', plaka: '36', ilceler: ['Merkez', 'Akyaka', 'Arpaçay', 'Digor', 'Kağızman', 'Sarıkamış', 'Selim', 'Susuz'] },
  { name: 'Kastamonu', plaka: '37', ilceler: ['Merkez', 'Abana', 'Ağlı', 'Araç', 'Azdavay', 'Bozkurt', 'Cide', 'Çatalzeytin', 'Daday', 'Devrekani', 'Doğanyurt', 'Hanönü', 'İhsangazi', 'İnebolu', 'Küre', 'Pınarbaşı', 'Şenpazar', 'Seydiler', 'Taşköprü', 'Tosya'] },
  { name: 'Kayseri', plaka: '38', ilceler: ['Merkez', 'Akkışla', 'Bünyan', 'Develi', 'Felahiye', 'İncesu', 'Pınarbaşı', 'Sarıoğlan', 'Sarız', 'Tomarza', 'Yahyalı', 'Yeşilhisar', 'Melikgazi', 'Kocasinan', 'Talas', 'Hacılar', 'Özvatan'] },
  { name: 'Kırklareli', plaka: '39', ilceler: ['Merkez', 'Babaeski', 'Demirköy', 'Kofçaz', 'Lüleburgaz', 'Pehlivanköy', 'Pınarhisar', 'Vize'] },
  { name: 'Kırşehir', plaka: '40', ilceler: ['Merkez', 'Akçakent', 'Akpınar', 'Boztepe', 'Çiçekdağı', 'Kaman', 'Mucur'] },
  { name: 'Kocaeli', plaka: '41', ilceler: ['Gebze', 'Gölcük', 'Kandıra', 'Karamürsel', 'Körfez', 'Derince', 'Başiskele', 'Çayırova', 'Darıca', 'Dilovası', 'İzmit', 'Kartepe', 'Karamürsel'] },
  { name: 'Konya', plaka: '42', ilceler: ['Merkez', 'Akşehir', 'Beyşehir', 'Bozkır', 'Cihanbeyli', 'Çumra', 'Doğanhisar', 'Ereğli', 'Güneysinir', 'Hadim', 'Ilgın', 'Kadınhanı', 'Karapınar', 'Kulu', 'Sarayönü', 'Seydişehir', 'Taşkent', 'Tuzlukçu', 'Yalıhüyük', 'Yunak', 'Akören', 'Altınekin', 'Derebucak', 'Hüyük', 'Karatay', 'Meram', 'Selçuklu'] },
  { name: 'Kütahya', plaka: '43', ilceler: ['Merkez', 'Altıntaş', 'Aslanapa', 'Çavdarhisar', 'Domaniç', 'Dumlupınar', 'Emet', 'Gediz', 'Hisarcık', 'Pazarlar', 'Simav', 'Şaphane', 'Tavşanlı'] },
  { name: 'Malatya', plaka: '44', ilceler: ['Merkez', 'Akçadağ', 'Arapgir', 'Arguvan', 'Battalgazi', 'Darende', 'Doğanşehir', 'Doğanyol', 'Hekimhan', 'Kale', 'Kuluncak', 'Pütürge', 'Yazıhan', 'Yeşilyurt'] },
  { name: 'Manisa', plaka: '45', ilceler: ['Merkez', 'Akhisar', 'Alaşehir', 'Demirci', 'Gördes', 'Kırkağaç', 'Kula', 'Salihli', 'Sarıgöl', 'Saruhanlı', 'Selendi', 'Soma', 'Turgutlu', 'Ahmetli', 'Gölmarmara', 'Köprübaşı', 'Şehzadeler', 'Yunusemre'] },
  { name: 'Kahramanmaraş', plaka: '46', ilceler: ['Merkez', 'Afşin', 'Andırın', 'Çağlayancerit', 'Ekinözü', 'Elbistan', 'Göksun', 'Nurhak', 'Pazarcık', 'Türkoğlu', 'Dulkadiroğlu', 'Onikişubat'] },
  { name: 'Mardin', plaka: '47', ilceler: ['Merkez', 'Dargeçit', 'Derik', 'Kızıltepe', 'Mazıdağı', 'Midyat', 'Nusaybin', 'Ömerli', 'Savur', 'Yeşilli', 'Artuklu'] },
  { name: 'Muğla', plaka: '48', ilceler: ['Merkez', 'Bodrum', 'Dalaman', 'Datça', 'Fethiye', 'Köyceğiz', 'Marmaris', 'Milas', 'Ortaca', 'Ula', 'Yatağan', 'Dalaman', 'Seydikemer'] },
  { name: 'Muş', plaka: '49', ilceler: ['Merkez', 'Bulanık', 'Hasköy', 'Korkut', 'Malazgirt', 'Varto'] },
  { name: 'Nevşehir', plaka: '50', ilceler: ['Merkez', 'Avanos', 'Derinkuyu', 'Gülşehir', 'Hacıbektaş', 'Kozaklı', 'Ürgüp', 'Acıgöl'] },
  { name: 'Niğde', plaka: '51', ilceler: ['Merkez', 'Altunhisar', 'Bor', 'Çamardı', 'Çiftlik', 'Ulukışla'] },
  { name: 'Ordu', plaka: '52', ilceler: ['Merkez', 'Akkuş', 'Aybastı', 'Çamaş', 'Çatalpınar', 'Çaybaşı', 'Fatsa', 'Gölköy', 'Gülyalı', 'Gürgentepe', 'İkizce', 'Kabadüz', 'Kabataş', 'Korgan', 'Kumru', 'Mesudiye', 'Perşembe', 'Ulubey', 'Ünye', 'Altınordu'] },
  { name: 'Rize', plaka: '53', ilceler: ['Merkez', 'Ardeşen', 'Çamlıhemşin', 'Çayeli', 'Derepazarı', 'Fındıklı', 'Güneysu', 'Hemşin', 'İkizdere', 'İyidere', 'Kalkandere', 'Pazar'] },
  { name: 'Sakarya', plaka: '54', ilceler: ['Adapazarı', 'Akyazı', 'Arifiye', 'Erenler', 'Ferizli', 'Geyve', 'Hendek', 'Karapürçek', 'Karasu', 'Kaynarca', 'Kocaali', 'Pamukova', 'Sapanca', 'Serdivan', 'Söğütlü', 'Taraklı', 'Adapazarı'] },
  { name: 'Samsun', plaka: '55', ilceler: ['Merkez', 'Alaçam', 'Asarcık', 'Atakum', 'Ayvacık', 'Bafra', 'Canik', 'Çarşamba', 'Havza', 'Kavak', 'Ladik', 'Ondokuzmayıs', 'Salıpazarı', 'Tekkeköy', 'Terme', 'Vezirköprü', 'Yakakent', 'İlkadım'] },
  { name: 'Siirt', plaka: '56', ilceler: ['Merkez', 'Baykan', 'Eruh', 'Kurtalan', 'Pervari', 'Şirvan', 'Tillo'] },
  { name: 'Sinop', plaka: '57', ilceler: ['Merkez', 'Ayancık', 'Boyabat', 'Dikmen', 'Durağan', 'Erfelek', 'Gerze', 'Saraydüzü', 'Türkeli'] },
  { name: 'Sivas', plaka: '58', ilceler: ['Merkez', 'Akıncılar', 'Altınyayla', 'Divriği', 'Doğanşar', 'Gemerek', 'Gölova', 'Gürün', 'Hafik', 'İmranlı', 'Kangal', 'Koyulhisar', 'Şarkışla', 'Suşehri', 'Ulaş', 'Yıldızeli', 'Zara'] },
  { name: 'Tekirdağ', plaka: '59', ilceler: ['Merkez', 'Çerkezköy', 'Çorlu', 'Ergene', 'Hayrabolu', 'Kapaklı', 'Malkara', 'Marmaraereğlisi', 'Muratlı', 'Saray', 'Şarköy', 'Süleymanpaşa'] },
  { name: 'Tokat', plaka: '60', ilceler: ['Merkez', 'Almus', 'Artova', 'Başçiftlik', 'Erbaa', 'Niksar', 'Reşadiye', 'Sulusaray', 'Turhal', 'Yeşilyurt', 'Zile', 'Pazar'] },
  { name: 'Trabzon', plaka: '61', ilceler: ['Merkez', 'Akçaabat', 'Araklı', 'Arsin', 'Beşikdüzü', 'Çarşıbaşı', 'Çaykara', 'Dernekpazarı', 'Düzköy', 'Hayrat', 'Köprübaşı', 'Maçka', 'Of', 'Şalpazarı', 'Sürmene', 'Tonya', 'Vakfıkebir', 'Yomra', 'Ortahisar'] },
  { name: 'Tunceli', plaka: '62', ilceler: ['Merkez', 'Çemişgezek', 'Hozat', 'Mazgirt', 'Nazımiye', 'Ovacık', 'Pertek', 'Pülümür'] },
  { name: 'Şanlıurfa', plaka: '63', ilceler: ['Merkez', 'Akçakale', 'Birecik', 'Bozova', 'Ceylanpınar', 'Halfeti', 'Hilvan', 'Siverek', 'Suruç', 'Viranşehir', 'Harran', 'Eyyübiye', 'Haliliye', 'Karaköprü'] },
  { name: 'Uşak', plaka: '64', ilceler: ['Merkez', 'Banaz', 'Eşme', 'Karahallı', 'Sivaslı', 'Ulubey'] },
  { name: 'Van', plaka: '65', ilceler: ['Merkez', 'Bahçesaray', 'Başkale', 'Çaldıran', 'Çatak', 'Edremit', 'Erciş', 'Gevaş', 'Gürpınar', 'Muradiye', 'Özalp', 'Saray', 'İpekyolu', 'Tuşba'] },
  { name: 'Yozgat', plaka: '66', ilceler: ['Merkez', 'Akdağmadeni', 'Aydıncık', 'Boğazlıyan', 'Çandır', 'Çayıralan', 'Çekerek', 'Kadışehri', 'Saraykent', 'Sarıkaya', 'Sorgun', 'Şefaatli', 'Yerköy', 'Yenifakılı'] },
  { name: 'Zonguldak', plaka: '67', ilceler: ['Merkez', 'Alaplı', 'Çaycuma', 'Devrek', 'Gökçebey', 'Kilimli', 'Kozlu', 'Kozluk', 'Ereğli'] },
  { name: 'Aksaray', plaka: '68', ilceler: ['Merkez', 'Ağaçören', 'Eskil', 'Gülağaç', 'Güzelyurt', 'Ortaköy', 'Sarıyahşi'] },
  { name: 'Bayburt', plaka: '69', ilceler: ['Merkez', 'Aydıntepe', 'Demirözü'] },
  { name: 'Karaman', plaka: '70', ilceler: ['Merkez', 'Ayrancı', 'Başyayla', 'Ermenek', 'Kazımkarabekir', 'Sarıveliler'] },
  { name: 'Kırıkkale', plaka: '71', ilceler: ['Merkez', 'Bahşılı', 'Balışeyh', 'Çelebi', 'Delice', 'Karakeçili', 'Keskin', 'Sulakyurt', 'Yahşihan'] },
  { name: 'Batman', plaka: '72', ilceler: ['Merkez', 'Beşiri', 'Gercüş', 'Hasankeyf', 'Kozluk', 'Sason'] },
  { name: 'Şırnak', plaka: '73', ilceler: ['Merkez', 'Beytüşşebap', 'Cizre', 'Güçlükonak', 'İdil', 'Silopi', 'Uludere'] },
  { name: 'Bartın', plaka: '74', ilceler: ['Merkez', 'Amasra', 'Kurucaşile', 'Ulus'] },
  { name: 'Ardahan', plaka: '75', ilceler: ['Merkez', 'Çıldır', 'Damal', 'Göle', 'Hanak', 'Posof'] },
  { name: 'Iğdır', plaka: '76', ilceler: ['Merkez', 'Aralık', 'Karakoyunlu', 'Tuzluca'] },
  { name: 'Yalova', plaka: '77', ilceler: ['Merkez', 'Altınova', 'Armutlu', 'Çınarcık', 'Çiftlikköy', 'Termal'] },
  { name: 'Karabük', plaka: '78', ilceler: ['Merkez', 'Eflani', 'Eskipazar', 'Ovacık', 'Safranbolu', 'Yenice'] },
  { name: 'Kilis', plaka: '79', ilceler: ['Merkez', 'Elbeyli', 'Musabeyli', 'Polateli'] },
  { name: 'Osmaniye', plaka: '80', ilceler: ['Merkez', 'Bahçe', 'Düziçi', 'Hasanbeyli', 'Kadirli', 'Sumbas', 'Toprakkale'] },
  { name: 'Düzce', plaka: '81', ilceler: ['Merkez', 'Akçakoca', 'Cumayeri', 'Çilimli', 'Gölyaka', 'Gümüşova', 'Kaynaşlı', 'Yığılca'] },
]

// İlçeleri il adına göre getir
export function getIlcelerByIl(ilName: string): string[] {
  const il = turkiyeIller.find(i => i.name === ilName)
  return il ? il.ilceler : []
}

