export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ trackingNumber: string }> }
) {
  // Check admin auth
  const session = await getServerSession(authOptions)
  if (!session || session.user.role !== 'ADMIN') {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  try {
    const { trackingNumber } = await params

    // Find order by tracking number
    const order = await prisma.order.findFirst({
      where: {
        cargoTrackingNo: trackingNumber,
      },
    })

    if (!order) {
      return NextResponse.json(
        { error: 'Order not found for this tracking number' },
        { status: 404 }
      )
    }

    // Generate HTML label that can be printed as PDF
    const htmlLabel = `
<!DOCTYPE html>
<html lang="tr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>DHL Shipping Label - ${trackingNumber}</title>
  <style>
    @media print {
      @page {
        size: A4;
        margin: 0.5cm;
      }
      body {
        margin: 0;
        padding: 0;
      }
    }
    body {
      font-family: Arial, sans-serif;
      max-width: 800px;
      margin: 20px auto;
      padding: 20px;
      border: 2px solid #000;
      background: white;
    }
    .header {
      text-align: center;
      border-bottom: 3px solid #FFCC00;
      padding-bottom: 15px;
      margin-bottom: 20px;
    }
    .header h1 {
      color: #D40511;
      margin: 0;
      font-size: 28px;
      font-weight: bold;
    }
    .header .subtitle {
      color: #666;
      font-size: 14px;
      margin-top: 5px;
    }
    .label-content {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 20px;
      margin: 20px 0;
    }
    .section {
      border: 1px solid #ddd;
      padding: 15px;
      background: #f9f9f9;
    }
    .section h3 {
      margin-top: 0;
      color: #D40511;
      font-size: 16px;
      border-bottom: 2px solid #FFCC00;
      padding-bottom: 5px;
    }
    .section p {
      margin: 8px 0;
      font-size: 14px;
    }
    .tracking-number {
      text-align: center;
      background: #FFCC00;
      padding: 15px;
      margin: 20px 0;
      border: 2px solid #000;
    }
    .tracking-number .label-text {
      font-size: 12px;
      color: #666;
      margin-bottom: 5px;
    }
    .tracking-number .number {
      font-size: 24px;
      font-weight: bold;
      letter-spacing: 2px;
      color: #000;
    }
    .barcode-area {
      text-align: center;
      margin: 20px 0;
      padding: 10px;
      border: 1px dashed #ccc;
    }
    .barcode-text {
      font-family: 'Courier New', monospace;
      font-size: 18px;
      letter-spacing: 3px;
      margin: 10px 0;
    }
    .footer {
      text-align: center;
      margin-top: 30px;
      padding-top: 15px;
      border-top: 1px solid #ddd;
      font-size: 12px;
      color: #666;
    }
    .zensticker-logo {
      text-align: center;
      font-size: 20px;
      font-weight: bold;
      color: #000;
      margin: 10px 0;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>DHL EXPRESS</h1>
    <div class="subtitle">International Shipping Label</div>
  </div>

  <div class="zensticker-logo">ZenSticker</div>

  <div class="tracking-number">
    <div class="label-text">TRACKING NUMBER</div>
    <div class="number">${trackingNumber}</div>
  </div>

  <div class="label-content">
    <div class="section">
      <h3>SHIP TO (RECIPIENT)</h3>
      <p><strong>${order.customerName}</strong></p>
      <p>${order.customerAddress.replace(/\n/g, '<br>')}</p>
      <p>Phone: ${order.customerPhone}</p>
      <p>Email: ${order.customerEmail}</p>
    </div>

    <div class="section">
      <h3>ORDER INFORMATION</h3>
      <p><strong>Order Number:</strong> ${order.orderNumber}</p>
      <p><strong>Order Date:</strong> ${new Date(order.createdAt).toLocaleDateString('tr-TR')}</p>
      <p><strong>Total Amount:</strong> ${order.totalAmount.toFixed(2)} ₺</p>
      <p><strong>Status:</strong> ${order.status}</p>
    </div>
  </div>

  <div class="barcode-area">
    <div class="barcode-text">${trackingNumber.replace(/-/g, '')}</div>
    <div style="font-size: 10px; color: #666;">Scan barcode for tracking</div>
  </div>

  <div class="footer">
    <p>This is a MOCK shipping label generated by ZenSticker</p>
    <p>For real DHL integration, this will be replaced with actual DHL label</p>
    <p>Generated on: ${new Date().toLocaleString('tr-TR')}</p>
  </div>
</body>
</html>
    `.trim()

    return new NextResponse(htmlLabel, {
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Disposition': `inline; filename="dhl-label-${trackingNumber}.html"`,
      },
    })
  } catch (error) {
    console.error('Error generating label:', error)
    return NextResponse.json(
      { error: 'Failed to generate label' },
      { status: 500 }
    )
  }
}

